# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/akif/Projects/EHB326E/Final/Final/Final.srcs/sources_1/ip/blk_mem_gen_0_4/blk_mem_gen_0.xci
# IP: The module: 'blk_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/akif/Projects/EHB326E/Final/Final/Final.srcs/sources_1/ip/blk_mem_gen_0_4/blk_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/akif/Projects/EHB326E/Final/Final/Final.srcs/sources_1/ip/blk_mem_gen_0_4/blk_mem_gen_0.xci
# IP: The module: 'blk_mem_gen_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/akif/Projects/EHB326E/Final/Final/Final.srcs/sources_1/ip/blk_mem_gen_0_4/blk_mem_gen_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'blk_mem_gen_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
